#!/bin/sh

LOGFILE=fics.log
HOST=hendrix.anu.edu.au
PORT=5000
OWNER=tridge
FICSHANDLE=tscp
FICSPASSWD=foobar
PROGRAM=./tscp
ROBOFICS=../robofics/robofics

export FICSHANDLE
export FICSPASSWD

while [ 1 ]; do
  $ROBOFICS -ficsHost $HOST -ficsPort $PORT -owner $OWNER -program \
   $PROGRAM >> $LOGFILE 2>&1
  sleep 60
done

